- name: Adds wazuh key
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: Adds wazuh repos
  apt_repository:
    repo: "deb https://packages.wazuh.com/apt {{ ansible_lsb.codename }} main"
    filename: /etc/apt/sources.list.d/wazuh.list

- name: Installs wazuh agent
  apt: pkg=wazuh-agent state=present

- name: Adds config file
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    mode: 0644
    owner: root
    group: ossec
  notify:
    - Restart wazuh-agent
